import { RepoStats } from "./scanner";

function formatBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  if (n < 1024 * 1024 * 1024) return `${(n / (1024 * 1024)).toFixed(1)} MB`;
  return `${(n / (1024 * 1024 * 1024)).toFixed(2)} GB`;
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, "\\|");
}

export function renderMarkdown(stats: RepoStats): string {
  const avgSize = stats.totalFiles ? Math.round(stats.totalBytes / stats.totalFiles) : 0;
  const avgLines = stats.totalFiles ? Math.round(stats.totalLines / stats.totalFiles) : 0;

  const lines: string[] = [];

  lines.push(`# Lumen Report — ${stats.rootName}`);
  lines.push("");
  lines.push(`> **Repository:** \`${stats.root}\`  `);
  lines.push(`> **Scanned:** ${stats.scannedAt}`);
  lines.push("");

  lines.push("## Summary");
  lines.push("");
  lines.push("| Metric | Value |");
  lines.push("| --- | ---: |");
  lines.push(`| Total files | ${stats.totalFiles.toLocaleString()} |`);
  lines.push(`| Total size | ${formatBytes(stats.totalBytes)} (avg ${formatBytes(avgSize)} / file) |`);
  lines.push(`| Lines of code | ${stats.totalLines.toLocaleString()} (avg ${avgLines.toLocaleString()} / file) |`);
  lines.push(`| Distinct extensions | ${stats.byExtension.length} |`);
  lines.push(`| Ignored directories | ${stats.ignored.length} |`);
  lines.push("");

  if (stats.notableFiles.length) {
    lines.push("## Notable files");
    lines.push("");
    for (const n of stats.notableFiles) {
      lines.push(`- **${escapeCell(n.name)}** — \`${escapeCell(n.relPath)}\` (${formatBytes(n.size)})`);
    }
    lines.push("");
  }

  lines.push("## File types");
  lines.push("");
  lines.push("| Extension | Files | Size | Lines |");
  lines.push("| --- | ---: | ---: | ---: |");
  for (const e of stats.byExtension.slice(0, 20)) {
    lines.push(
      `| \`${escapeCell(e.ext)}\` | ${e.files} | ${formatBytes(e.bytes)} | ${e.lines.toLocaleString()} |`,
    );
  }
  lines.push("");

  if (stats.topDirectories.length) {
    lines.push("## Top directories");
    lines.push("");
    lines.push("| Directory | Files | Size |");
    lines.push("| --- | ---: | ---: |");
    for (const d of stats.topDirectories) {
      lines.push(`| \`${escapeCell(d.dir)}\` | ${d.files} | ${formatBytes(d.bytes)} |`);
    }
    lines.push("");
  }

  if (stats.largestFiles.length) {
    lines.push("## Largest files");
    lines.push("");
    lines.push("| Path | Size |");
    lines.push("| --- | ---: |");
    for (const f of stats.largestFiles) {
      lines.push(`| \`${escapeCell(f.relPath)}\` | ${formatBytes(f.size)} |`);
    }
    lines.push("");
  }

  if (stats.ignored.length) {
    lines.push("<details>");
    lines.push("<summary>Ignored directories</summary>");
    lines.push("");
    for (const i of stats.ignored) {
      lines.push(`- \`${escapeCell(i)}\``);
    }
    lines.push("");
    lines.push("</details>");
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("_Generated by [lumen](https://www.npmjs.com/package/@ajmal_n/lumen-cli)._");

  return lines.join("\n") + "\n";
}
