import { renderMarkdown } from "../src/markdown";
import { CoverageReport } from "../src/coverage";
import { RepoStats } from "../src/scanner";

const stats: RepoStats = {
  root: "/tmp/demo",
  rootName: "demo",
  scannedAt: "2026-01-01T00:00:00.000Z",
  totalFiles: 3,
  totalBytes: 1024,
  totalLines: 200,
  largestFiles: [
    { relPath: "src/big.ts", size: 800, lines: 150, ext: ".ts" },
    { relPath: "src/small.ts", size: 200, lines: 30, ext: ".ts" },
    { relPath: "README.md", size: 24, lines: 20, ext: ".md" },
  ],
  byExtension: [
    { ext: ".ts", files: 2, bytes: 1000, lines: 180 },
    { ext: ".md", files: 1, bytes: 24, lines: 20 },
  ],
  topDirectories: [{ dir: "src", files: 2, bytes: 1000 }],
  notableFiles: [{ name: "README.md", relPath: "README.md", size: 24 }],
  ignored: ["node_modules"],
};

const coverage: CoverageReport = {
  root: "/tmp/demo",
  framework: "jest",
  sources: ["coverage/coverage-summary.json"],
  total: {
    lines: { total: 200, covered: 160, pct: 80 },
    statements: { total: 200, covered: 160, pct: 80 },
    functions: { total: 30, covered: 24, pct: 80 },
    branches: { total: 80, covered: 60, pct: 75 },
  },
  files: [
    {
      path: "src/big.ts",
      lines: { total: 150, covered: 60, pct: 40 },
      statements: { total: 150, covered: 60, pct: 40 },
      functions: { total: 20, covered: 10, pct: 50 },
      branches: { total: 60, covered: 30, pct: 50 },
    },
    {
      path: "src/small.ts",
      lines: { total: 50, covered: 50, pct: 100 },
      statements: { total: 50, covered: 50, pct: 100 },
      functions: { total: 10, covered: 10, pct: 100 },
      branches: { total: 20, covered: 20, pct: 100 },
    },
  ],
};

describe("renderMarkdown", () => {
  test("starts with H1 containing the repo name", () => {
    const md = renderMarkdown(stats);
    expect(md.split("\n")[0]).toBe("# Lumen Report — demo");
  });

  test("renders the summary table with file/line counts", () => {
    const md = renderMarkdown(stats);
    expect(md).toContain("| Total files | 3 |");
    expect(md).toContain("| Distinct extensions | 2 |");
  });

  test("includes notable files section when present", () => {
    const md = renderMarkdown(stats);
    expect(md).toContain("## Notable files");
    expect(md).toContain("**README.md**");
  });

  test("omits coverage section when coverage is null", () => {
    const md = renderMarkdown(stats, { coverage: null });
    expect(md).not.toContain("## Test coverage");
  });

  test("includes coverage section when coverage is supplied", () => {
    const md = renderMarkdown(stats, { coverage });
    expect(md).toContain("## Test coverage — jest");
    expect(md).toContain("80.00% (160 / 200)");
  });

  test("renders threshold pass/fail when threshold provided", () => {
    const pass = renderMarkdown(stats, { coverage, threshold: 70 });
    expect(pass).toContain(":white_check_mark: passed");

    const fail = renderMarkdown(stats, { coverage, threshold: 90 });
    expect(fail).toContain(":x: failed");
  });

  test("renders an AI Analysis section when aiSummary is provided", () => {
    const md = renderMarkdown(stats, {
      aiSummary: { model: "claude-sonnet-4-6", text: "Looks good.\n\nSuggest more tests." },
    });
    expect(md).toContain("## AI Analysis — claude-sonnet-4-6");
    expect(md).toContain("> Looks good.");
    expect(md).toContain("> Suggest more tests.");
  });

  test("does not render AI Analysis when text is empty", () => {
    const md = renderMarkdown(stats, {
      aiSummary: { model: "x", text: "   " },
    });
    expect(md).not.toContain("AI Analysis");
  });

  test("includes a footer attribution", () => {
    const md = renderMarkdown(stats);
    expect(md).toMatch(/Generated by \[lumen\]/);
  });

  test("sorts worst-covered files first in the lowest-coverage list", () => {
    const md = renderMarkdown(stats, { coverage });
    const big = md.indexOf("src/big.ts");
    const small = md.indexOf("src/small.ts");
    expect(big).toBeGreaterThan(-1);
    expect(small).toBeGreaterThan(-1);
    expect(big).toBeLessThan(small);
  });
});
